CREATE DATABASE INVENTORY
GO

USE INVENTORY
GO

CREATE TABLE CITY(
  IDCITY INT  IDENTITY(1000,1),
  NAMECITY VARCHAR(30) NOT NULL,
  PROVINCE CHAR(2) NOT NULL,
  PRIMARY KEY(IDCITY)
)
GO

CREATE TABLE CATEGORY(
  IDCATEGORY INT  IDENTITY(2000,1) ,
  NAMECATEGORY VARCHAR(30) NOT NULL,
  PRIMARY KEY(IDCATEGORY)
)
GO

CREATE TABLE SHIPPING_COMPANY(
  IDSHIPPING_COMPANY INT  IDENTITY(3000,1),
  NAMECOMPANY VARCHAR(30) NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  PHONENUMBER VARCHAR(20) NOT NULL,
  ID_CITY INT  NOT NULL
  PRIMARY KEY(IDSHIPPING_COMPANY),
  FOREIGN KEY (ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE WAREHOUSE(
  IDWAREHOUSE INT IDENTITY(4000,1),
  NAMEWAREHOUSE VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(50) NULL,
  ID_CITY INT  NOT NULL
  PRIMARY KEY(IDWAREHOUSE),
  FOREIGN KEY (ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE IN_ORDER(
  IDIN_ORDER INT IDENTITY(5000,1),
  ID_SHIPPING_COMPANY INT  NOT NULL,
  DATE DATE NULL,
  PRIMARY KEY(IDIN_ORDER),
  FOREIGN KEY (ID_SHIPPING_COMPANY) REFERENCES SHIPPING_COMPANY(IDSHIPPING_COMPANY)
)
GO

CREATE TABLE OUT_ORDER(
  IDOUT_ORDER INT IDENTITY(7000,1),
  ID_SHIPPING_COMPANY INT  NOT NULL,
  DATE DATE NULL,
  ID_WAREHOUSE INT NOT NULL,  
  PRIMARY KEY(IDOUT_ORDER),
  FOREIGN KEY(ID_SHIPPING_COMPANY) REFERENCES SHIPPING_COMPANY(IDSHIPPING_COMPANY),
  FOREIGN KEY(ID_WAREHOUSE) REFERENCES WAREHOUSE(IDWAREHOUSE)
)
GO

CREATE TABLE SUPPLIER(
  IDSUPPLIER INT IDENTITY(6000,1) ,
  NAMESUPPLIER VARCHAR(50) NULL,
  ID_CITY INT  NOT NULL,  
  ADDRESS VARCHAR(50) NULL,
  PRIMARY KEY(IDSUPPLIER),
  FOREIGN KEY(ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE PRODUCT(
  IDPRODUCT INT  NOT NULL,
  PRODUCT VARCHAR(255) NULL,
  ID_CATEGORY INT  NOT NULL,
  ID_SUPPLIER INT  NOT NULL,
  MIN_QUANTITY INT  NULL,
  PRIMARY KEY(IDPRODUCT),
  FOREIGN KEY(ID_SUPPLIER) REFERENCES SUPPLIER(IDSUPPLIER),
  FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(IDCATEGORY)
)
GO

CREATE TABLE IN_ITEM_ORDER(
  IDIN_ITEM_ORDER INT  NOT NULL ,
  ID_PRODUCT INT  NOT NULL,
  ID_INORDER INT  NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE REAL NOT NULL,
  PRIMARY KEY(IDIN_ITEM_ORDER),
  FOREIGN KEY(ID_INORDER) REFERENCES IN_ORDER(IDIN_ORDER),
  FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(IDPRODUCT)
)
GO

CREATE TABLE OUT_ITEM_ORDER(
  IDOUT_ITEM_ORDER INT  NOT NULL ,
  ID_PRODUCT INT  NOT NULL,
  ID_OUTORDER INT  NOT NULL,
  QUANTITY INT  NOT NULL,
  PRICE REAL NOT NULL,
  PRIMARY KEY(IDOUT_ITEM_ORDER),
  FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(IDPRODUCT),
  FOREIGN KEY(ID_OUTORDER) REFERENCES OUT_ORDER(IDOUT_ORDER)
)
GO