CREATE DATABASE INVENTORY
GO

USE INVENTORY
GO

CREATE TABLE EMPLOYEE(
	IDEMPLOYEE INT PRIMARY KEY IDENTITY,
	NAME VARCHAR(30) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL UNIQUE,
	GENDER CHAR(1) NOT NULL,
	ROLE VARCHAR(20) NOT NULL
)
GO

CREATE TABLE CITY(
  IDCITY INT  IDENTITY(1000,1),
  NAMECITY VARCHAR(30) NOT NULL,
  PROVINCE CHAR(2) NOT NULL,
  PRIMARY KEY(IDCITY)
)
GO

CREATE TABLE CATEGORY(
  IDCATEGORY INT  IDENTITY(2000,1),
  NAMECATEGORY VARCHAR(30) NOT NULL,
  PRIMARY KEY(IDCATEGORY)
)
GO

CREATE TABLE SHIPPING_COMPANY(
  IDSHIPPING_COMPANY INT  IDENTITY(3000,1),
  NAMECOMPANY VARCHAR(30) NULL,
  ADDRESS VARCHAR(255) NOT NULL,
  PHONENUMBER VARCHAR(20) NOT NULL,
  ID_CITY INT  NOT NULL
  PRIMARY KEY(IDSHIPPING_COMPANY),
  FOREIGN KEY (ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE STORE(
  IDSTORE INT IDENTITY(4000,1),
  NAMESTORE VARCHAR(50) NOT NULL,
  ADDRESS VARCHAR(50) NULL,
  ID_CITY INT  NOT NULL
  PRIMARY KEY(IDSTORE),
  FOREIGN KEY (ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE SUPPLIER(
  IDSUPPLIER INT IDENTITY(6000,1) ,
  NAMESUPPLIER VARCHAR(50) NULL,
  ID_CITY INT  NOT NULL,  
  ADDRESS VARCHAR(50) NULL,
  PRIMARY KEY(IDSUPPLIER),
  FOREIGN KEY(ID_CITY) REFERENCES CITY(IDCITY)
)
GO

CREATE TABLE IN_ORDER(
  IDIN_ORDER INT IDENTITY(5000,1),
  ID_SHIPPING_COMPANY INT  NOT NULL,
  ID_SUPPLIER INT NOT NULL,
  ID_EMPLOYEE INT NOT NULL,
  DATE DATE NULL,
  PRIMARY KEY(IDIN_ORDER),
  FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE),
  FOREIGN KEY (ID_SHIPPING_COMPANY) REFERENCES SHIPPING_COMPANY(IDSHIPPING_COMPANY),
  FOREIGN KEY (ID_SUPPLIER) REFERENCES SUPPLIER(IDSUPPLIER),
)
GO

CREATE TABLE OUT_ORDER(
  IDOUT_ORDER INT IDENTITY(7000,1),
  ID_SHIPPING_COMPANY INT  NOT NULL,
  ID_STORE INT NOT NULL, 
  ID_EMPLOYEE INT NOT NULL,
  DATE DATE NULL,
  FOREIGN KEY (ID_EMPLOYEE) REFERENCES EMPLOYEE(IDEMPLOYEE),
  PRIMARY KEY(IDOUT_ORDER),
  FOREIGN KEY(ID_SHIPPING_COMPANY) REFERENCES SHIPPING_COMPANY(IDSHIPPING_COMPANY),
  FOREIGN KEY(ID_STORE) REFERENCES STORE(IDSTORE)
)
GO

CREATE TABLE PRODUCT(
  IDPRODUCT INT  IDENTITY,
  PRODUCT VARCHAR(255) NULL,
  ID_CATEGORY INT  NOT NULL,
  PRIMARY KEY(IDPRODUCT),
  FOREIGN KEY(ID_CATEGORY) REFERENCES CATEGORY(IDCATEGORY)
)
GO

CREATE TABLE IN_ITEM_ORDER(
  IDIN_ITEM_ORDER INT  IDENTITY,
  ID_PRODUCT INT  NOT NULL,
  ID_INORDER INT  NOT NULL,
  QUANTITY INT NOT NULL,
  PRICE REAL NOT NULL,
  PRIMARY KEY(IDIN_ITEM_ORDER),
  FOREIGN KEY(ID_INORDER) REFERENCES IN_ORDER(IDIN_ORDER),
  FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(IDPRODUCT)
)
GO

CREATE TABLE CUSTOMER_ORDER(
  IDCUSTOMER_ORDER INT IDENTITY,
  DATE DATE NULL,
  ID_STORE INT,
  PRIMARY KEY(IDCUSTOMER_ORDER),
  FOREIGN KEY(ID_STORE) REFERENCES STORE(IDSTORE)
)
GO

CREATE TABLE CUSTOMER_ITEM(
  IDOUT_ITEM_ORDER INT IDENTITY,
  ID_PRODUCT INT  NOT NULL,
  ID_CUSTOMER_ORDER INT  NOT NULL,
  QUANTITY INT  NOT NULL,
  PRICE REAL NOT NULL,
  PRIMARY KEY(IDOUT_ITEM_ORDER),
  FOREIGN KEY(ID_PRODUCT) REFERENCES PRODUCT(IDPRODUCT),
  FOREIGN KEY(ID_CUSTOMER_ORDER) REFERENCES CUSTOMER_ORDER(IDCUSTOMER_ORDER)
)
GO



SELECT PRODUCT, QUANTITY
FROM PRODUCT P
INNER JOIN IN_ITEM_ORDER
ON IDPRODUCT = ID_PRODUCT
INNER JOIN IN_ORDER
ON ID_INORDER = IDIN_ITEM_ORDER

SELECT * FROM PRODUCT
SELECT * FROM IN_ITEM_ORDER
SELECT * FROM IN_ORDER

SELECT PRODUCT, ID_INORDER, ID_PRODUCT, QUANTITY, PRICE
FROM IN_ORDER
INNER JOIN IN_ITEM_ORDER
ON ID_INORDER = IDIN_ORDER
INNER JOIN PRODUCT
ON IDPRODUCT = ID_PRODUCT

SELECT PRODUCT,  SUM(QUANTITY) AS TOTAL_QUANTITY
FROM IN_ORDER
INNER JOIN IN_ITEM_ORDER
ON ID_INORDER = IDIN_ORDER
INNER JOIN PRODUCT
ON IDPRODUCT = ID_PRODUCT
GROUP BY PRODUCT


